var express = require('express');
var app = express();

app.set('port', (process.env.PORT || 5000));

var bodyParser = require('body-parser');
app.use(bodyParser.json()); //soporte para codificar json
app.use(bodyParser.urlencoded({ 
	extended: true 
})); //Soporte para decodificar las url

//var firebase = require("firebase");
//firebase.initializeApp({
//	serviceAccount: "Luminer-bab78d4d4524.json",
//	databaseURL: "https://luminer-v1.firebaseio.com"
//});

var admin = require("firebase-admin");

admin.initializeApp({
  credential: admin.credential.cert("Luminer-9d6336a3a028.json"),
  databaseURL: "https://luminer-v1.firebaseio.com"
});


var FCM = require('fcm-push');



app.use(express.static(__dirname + '/public'));

// views is directory for all template files
app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');

app.get('/android', function(request, response) {
  response.render('pages/index');
});




//post
//https://warm-atoll-90602.herokuapp.com/token-device
//token
var tokenDevicesURI = "token-device";
app.post('/'+tokenDevicesURI, function(request, response){
	var token = request.body.token;
	var animal = request.body.animal;

	var db = admin.database();
	var tokenDevices = db.ref(tokenDevicesURI).push();

	tokenDevices.set({
		token: token,
		animal: animal
	});

	var path = tokenDevices.toString(); //devuelve toda la direccion + el identificador del registro
	var pathSplit = path.split(tokenDevicesURI + "/");
	var idAutoGenerated = pathSplit[1];

	var respuesta = generateResponseToToken(db,idAutoGenerated);
	response.setHeader("Content-Type", "application/json");
	response.send(JSON.stringify(respuesta));
});


function generateResponseToToken(db,idAutoGenerated){
	var respuesta = {};
	var usuario = "";
	var ref = db.ref("token-device");
	ref.on("child_added",function(snapshot, prevChildKey){
		usuario = snapshot.val();
		respuesta = {
			id: idAutoGenerated,
			token: usuario.token,
			animal: usuario.animal
		};
	});
	return respuesta;
}

//GET
//https://warm-atoll-90602.herokuapp.com/toque-animal
//id
//animal
app.get("/toque-animal/:id/:animal", function(request,response){
	var id = request.params.id;
	var animal = request.params.animal;

	var db = admin.database();
	var ref = db.ref("token-device/" + id);
	var usuario = ""

	var respuesta = {};

	ref.on("value", function(snapshot) {
			console.log(snapshot.val());
			usuario = snapshot.val();
			var mensaje = usuario.animal + "te dio un toque";
			enviarNotificacion(usuario.token, mensaje);
			respuesta = {
				id: id,
				token: usuario.token,
				animal: usuario.animal
		};
		response.send(JSON.stringify(respuesta));
	}, function(errorObject){
			console.log("The read failed: " + errorObject.code);
			respuesta = {
				id: "",
				token: "",
				animal: ""
			};
			response.send(JSON.stringify(respuesta));

	});
});


function enviarNotificacion(tokenDestinatario, mensaje){

	var serverKey = 'AIzaSyA6AxmCDGAPLHEaecPrEKV-F5YrS3JeeTY';
	var fcm = new FCM(serverKey);

	var message = {
	    to: tokenDestinatario, // required fill with device token or topics
	    collapse_key: '', 
	    data: {},
	    notification: {
	        title: 'Notificacion desde el servidor',
	        body: mensaje,
	        icon: "bitcoin_in_processor",
	        sound:"default",
	        color:"#00BCD4"
	    }
	};

	//callback style
	fcm.send(message, function(err, response){
	    if (err) {
	        console.log("Something has gone wrong!");
	    } else {
	        console.log("Successfully sent with response: ", response);
	    }
	});

};


app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});
