var express = require('express');
var app = express();

app.set('port', (process.env.PORT || 5000));

var bodyParser = require('body-parser');
app.use(bodyParser.json()); //soporte para codificar json
app.use(bodyParser.urlencoded({ 
	extended: true 
})); //Soporte para decodificar las url


var admin = require("firebase-admin");
admin.initializeApp({
  credential: admin.credential.cert("Luminer-9d6336a3a028.json"),
  databaseURL: "https://luminer-v1.firebaseio.com"
});


var FCM = require('fcm-push'); 

app.use(express.static(__dirname + '/public'));

// views is directory for all template files
app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');

app.get('/android', function(request, response) {
  response.render('pages/index');
});

//POST
//https://warm-atoll-90602.herokuapp.com/token-miner
//token
//Registrar el token del minero en firebase
var tokenMinerURI = "token-miner";
app.post('/'+tokenMinerURI, function(request, response){
	var token = request.body.token;
	var propietario = request.body.propietario;

	var db = admin.database();
	var tokenMiner = db.ref(tokenMinerURI).push();

	tokenMiner.set({
		token: token,
		propietario: propietario,
		online: "true",
		gpu0:""
	});

	var path = tokenMiner.toString(); //devuelve toda la direccion + el identificador del registro
	var pathSplit = path.split(tokenMinerURI + "/");
	var idAutoGenerated = pathSplit[1];

	var respuesta = generateResponseToTokenMiner(db,idAutoGenerated);
	response.setHeader("Content-Type", "application/json");
	response.send(JSON.stringify(respuesta));
});

function generateResponseToTokenMiner(db,idAutoGenerated){
	var respuesta = {};
	var usuario = "";
	var ref = db.ref("token-miner");
	ref.on("child_added",function(snapshot, prevChildKey){
		usuario = snapshot.val();
		respuesta = {
			id: idAutoGenerated,
			token: usuario.token,
		};
	});
	return respuesta;
}



//POST
//https://warm-atoll-90602.herokuapp.com/token-device
//token
//Registrar el token de dispositivo android en firebase
var tokenDevicesURI = "token-device";
app.post('/'+tokenDevicesURI, function(request, response){
	var token = request.body.token;
	var animal = request.body.animal;

	var db = admin.database();
	var tokenDevices = db.ref(tokenDevicesURI).push();

	tokenDevices.set({
		token: token,
		propietario: propietario,
		identificador: identificador,
	});

	var path = tokenDevices.toString(); //devuelve toda la direccion + el identificador del registro
	var pathSplit = path.split(tokenDevicesURI + "/");
	var idAutoGenerated = pathSplit[1];

	var respuesta = generateResponseToToken(db,idAutoGenerated);
	response.setHeader("Content-Type", "application/json");
	response.send(JSON.stringify(respuesta));
});


function generateResponseToToken(db,idAutoGenerated){
	var respuesta = {};
	var usuario = "";
	var ref = db.ref("token-device");
	ref.on("child_added",function(snapshot, prevChildKey){
		usuario = snapshot.val();
		respuesta = {
			id: idAutoGenerated,
			identificador: usuario.identificador,
			token: usuario.token,
			propietario: usuario.propietario

		};
	});
	return respuesta;
}



//GET
////https://warm-atoll-90602.herokuapp.com/miner-alert
//miner
//alert
app.get("/miner-alert/:miner/:alert", function(request,response){
	var miner = request.params.miner;
	var alert = request.params.alert;

	var db = admin.database();
	var ref = db.ref("token-device");
	var usuario = ""

	var respuesta = {};

	ref.orderByChild("miner").equalTo(miner).on("child_added", function(snapshot) {
  		console.log(snapshot.key);
  		console.log(snapshot.val());

  		usuario = snapshot.val();

  		var mensaje = "El minero " + miner + " ha generado un error: " + alert; //alert: alta temperatura en GPU0
  		enviarNotificacion(usuario.token, mensaje);

  		respuesta = {
			miner: miner,
			token: usuario.token,
			alert: alert
		};

		response.send(JSON.stringify(respuesta));
	}, function(errorObject){
		console.log("The read failed: " + errorObject.code);
		respuesta = {
			miner: "",
			token: "",
			alert: ""
		};
		response.send(JSON.stringify(respuesta));
	});
});


//GET
////https://warm-atoll-90602.herokuapp.com/miner-alert2
//miner
//alert
app.get("/miner-alert2/:miner/:alert", function(request,response){
	var miner = request.params.miner;
	var alert = request.params.alert;

	var db = admin.database();
	var ref = db.ref("token-device");
	var usuario = ""

	var respuesta = {};


	ref.orderByChild("miner").equalTo(miner) .on("child_added", function(data) {
	   console.log(data.val() .token);
	   response.send(JSON.stringify(data));
	});


	/*ref.orderByValue() .on("value", function(data) {
	   data.forEach(function(data) {
	      console.log("The " + data.key + " is " + data.val().token );

	   });

	   response.send(JSON.stringify(data))
	});
*/

	/*ref.orderByChild("token").on("child_added", function(snapshot) {
  		
  		console.log(snapshot.val() .token);

  		usuario = snapshot.val();

  		var mensaje = "El minero " + miner + " ha generado un error: " + alert; //alert: alta temperatura en GPU0
  		//enviarNotificacion(usuario.token, mensaje);

  		respuesta = {
			miner: miner,
			token: usuario.token,
			alert: alert
		};

		response.send(JSON.stringify(respuesta));

	}, function(errorObject){
		console.log("The read failed: " + errorObject.code);
		respuesta = {
			miner: "",
			token: "",
			alert: ""
		};
		response.send(JSON.stringify(respuesta));
	});*/
});





//GET
//https://warm-atoll-90602.herokuapp.com/toque-animal
//id
//animal
app.get("/toque-animal/:id/:animal", function(request,response){
	var id = request.params.id;
	var animal = request.params.animal;

	var db = admin.database();
	var ref = db.ref("token-device/" + id);
	var usuario = ""

	var respuesta = {};

	ref.on("value", function(snapshot) {
		console.log(snapshot.val());
		usuario = snapshot.val();
		var mensaje = usuario.animal + "te dio un toque";
		enviarNotificacion(usuario.token, mensaje);
		respuesta = {
			id: id,
			token: usuario.token,
			animal: animal
		};
		response.send(JSON.stringify(respuesta));
	}, function(errorObject){
		console.log("The read failed: " + errorObject.code);
		respuesta = {
			id: "",
			token: "",
			animal: ""
		};
		response.send(JSON.stringify(respuesta));
	});
});


function enviarNotificacion(tokenDestinatario, mensaje){

	var serverKey = 'AIzaSyA6AxmCDGAPLHEaecPrEKV-F5YrS3JeeTY';
	var fcm = new FCM(serverKey);

	var message = {
	    to: tokenDestinatario, // required fill with device token or topics
	    collapse_key: '', 
	    data: {},
	    notification: {
	        title: 'Notificacion desde el servidor',
	        body: mensaje,
	        icon: "bitcoin_in_processor",
	        sound:"default",
	        color:"#00BCD4"
	    }
	};

	//callback style
	fcm.send(message, function(err, response){
	    if (err) {
	        console.log("Something has gone wrong!");
	    } else {
	        console.log("Successfully sent with response: ", response);
	    }
	});

};


app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});
